/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 books.gltf 
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/expo-books-0e112c9515c04ef1b35d50094438276b
Title: Expo Books
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const meshRef=useRef()
  useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.y += 0.01
     
    }
  })
  
  const { nodes, materials } = useGLTF('/books.gltf')
  return (
    <group {...props} dispose={null} scale={0.0023} ref={meshRef} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-731.962, -726.447, -1.177]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Expositor1} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.books_4} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.books_5} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.books_6} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.pages} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/books.gltf')
